generate_xlsx_blueprint/generate_xlsx_blueprint.py
from flask import Blueprint, send_file, session, request, render_template
import xlsxwriter
import datetime

from models.models import *
from . import exec_data

generate_xlsx_blueprint = Blueprint('GEN_XLSX_bp', __name__, static_folder = 'static', template_folder = 'templates')

@generate_xlsx_blueprint.route('/generate/<int:current_page_url>')
def generate_xlsx(current_page_url = 1):
    return_para = {}

    exec_all_booking_room = exec_data.get_all_booking_room(current_page_url)
    if exec_all_booking_room != False:
        return_para['get_all_booking'] = exec_all_booking_room['get_all_booking']
        return_para['pagination_page'] = exec_all_booking_room['pagination_page']
    
    return_para['current_page'] = current_page_url

    return render_template('generate_xlsx_view.html', **return_para)

@generate_xlsx_blueprint.route('/get-excel-all')
def download_xlsx_all():
    workbook = xlsxwriter.Workbook('demo.xlsx')
    worksheet = workbook.add_worksheet()

    worksheet.write(0,0,'id booking room')
    worksheet.write(0,1,'id users')
    worksheet.write(0,2,'id all room')
    worksheet.write(0,3,'time booking')
    worksheet.write(0,4,'time start')
    worksheet.write(0,5,'default service')
    worksheet.write(0,6,'option service')
    worksheet.write(0,7,'minute rent')
    worksheet.write(0,8,'status')
    worksheet.write(0,9,'total price')
    worksheet.write(0,10,'option service price')
    worksheet.write(0,11,'note booking')
    worksheet.write(0,12,'code booking')
    worksheet.write(0,13,'billing option')
    worksheet.write(0,14,'flag booking')

    row = 1

    exec_all_booking_room = exec_data.get_all_booking_room_without_pagination()

    if exec_all_booking_room != False:
        get_all_booking_room = exec_all_booking_room['get_all_booking_room']

        for index in get_all_booking_room:
            col = 0
            for subindex in index:
                worksheet.write(row, col, str(subindex))
                col = col + 1
            row = row + 1

    workbook.close()
    return send_file('demo.xlsx', as_attachment=True)

@generate_xlsx_blueprint.route('/get-excel-current-page/<int:current_page_url>')
def download_xlsx_current_page(current_page_url = 1):
    workbook = xlsxwriter.Workbook('demo.xlsx')
    worksheet = workbook.add_worksheet()

    worksheet.write(0,0,'id booking room')
    worksheet.write(0,1,'id users')
    worksheet.write(0,2,'id all room')
    worksheet.write(0,3,'time booking')
    worksheet.write(0,4,'time start')
    worksheet.write(0,5,'default service')
    worksheet.write(0,6,'option service')
    worksheet.write(0,7,'minute rent')
    worksheet.write(0,8,'status')
    worksheet.write(0,9,'total price')
    worksheet.write(0,10,'option service price')
    worksheet.write(0,11,'note booking')
    worksheet.write(0,12,'code booking')
    worksheet.write(0,13,'billing option')
    worksheet.write(0,14,'flag booking')

    row = 1

    exec_all_booking_room = exec_data.get_all_booking_room(current_page_url)

    if exec_all_booking_room != False:
        get_all_booking_room = exec_all_booking_room['get_all_booking']

        for index in get_all_booking_room:
            col = 0
            for subindex in index:
                worksheet.write(row, col, str(subindex))
                col = col + 1
            row = row + 1

    workbook.close()
    return send_file('demo.xlsx', as_attachment=True)

generate_xlsx_blueprint/templates/download_pdf_all_page.html
<link rel="stylesheet" href="{{url_for('GEN_PDF_bp.static', filename = 'css/generate_pdf_view.css')}}">
<div class="show__all__booking__room">
    <table>
        <tr>
            <th>No</th>
            <th>ID User</th>
            <th>ID Room</th>
            <th>Time Booking</th>
            <th>Time Start</th>
            <th>Default Service</th>
            <th>Option Service</th>
            <th>Minute Rent</th>
            <th>Status</th>
            <th>Total Price</th>
            <th>Option Service Price</th>
            <th>Code Booking</th>
            <th>Billing Option</th>
        </tr>
        {% for each_booking in get_all_booking_room %}
            <tr>
                <td>{{loop.index}}</td>
                <td>{{each_booking.id_users}}</td>
                <td>{{each_booking.id_all_room}}</td>
                <td>{{each_booking.time_booking}}</td>
                <td>{{each_booking.time_start}}</td>
                <td>
                    {% for each_default_service in each_booking.default_service %}
                        <p>{{each_default_service}}</p>
                    {% endfor %}
                </td>
                <td>
                    {% for each_option_service in each_booking.option_service %}
                        <p>{{each_option_service    }}</p>
                    {% endfor %}
                </td>
                <td>{{each_booking.minute_rent}}</td>
                <td>{{each_booking.status}}</td>
                <td>{{each_booking.total_price}}</td>
                <td>{{each_booking.option_service_price}}</td>
                <td>{{each_booking.code_booking}}</td>
                <td>{{each_booking.billing_option}}</td>
            </tr>
        {% endfor %}
    </table>
</div>

generate_xlsx_blueprint/templates/download_pdf_current_page.html
<link rel="stylesheet" href="{{url_for('GEN_PDF_bp.static', filename = 'css/generate_pdf_view.css')}}">
<div class="show__all__booking__room">
    <table>
        <tr>
            <th>No</th>
            <th>ID User</th>
            <th>ID Room</th>
            <th>Time Booking</th>
            <th>Time Start</th>
            <th>Default Service</th>
            <th>Option Service</th>
            <th>Minute Rent</th>
            <th>Status</th>
            <th>Total Price</th>
            <th>Option Service Price</th>
            <th>Code Booking</th>
            <th>Billing Option</th>
        </tr>
        {% for each_booking in get_all_booking_room %}
            <tr>
                <td>{{loop.index}}</td>
                <td>{{each_booking.id_users}}</td>
                <td>{{each_booking.id_all_room}}</td>
                <td>{{each_booking.time_booking}}</td>
                <td>{{each_booking.time_start}}</td>
                <td>
                    {% for each_default_service in each_booking.default_service %}
                        <p>{{each_default_service}}</p>
                    {% endfor %}
                </td>
                <td>
                    {% for each_option_service in each_booking.option_service %}
                        <p>{{each_option_service    }}</p>
                    {% endfor %}
                </td>
                <td>{{each_booking.minute_rent}}</td>
                <td>{{each_booking.status}}</td>
                <td>{{each_booking.total_price}}</td>
                <td>{{each_booking.option_service_price}}</td>
                <td>{{each_booking.code_booking}}</td>
                <td>{{each_booking.billing_option}}</td>
            </tr>
        {% endfor %}
    </table>
</div>

generate_xlsx_blueprint/templates/generate_xlsx_view.html
<link rel="stylesheet" href="{{url_for('GEN_XLSX_bp.static', filename = 'css/generate_xlsx_view.css')}}">
<link rel="stylesheet" href="{{url_for('GEN_XLSX_bp.static', filename = 'css/show_pagination_page.css')}}">
<script src="{{url_for('GEN_XLSX_bp.static', filename = 'javascript/get_pagination.js')}}"></script>
<script>
    // document.getElementsByClassName('option__left__content')[2].classList.add('active__left__content__link') 
    var current_page = parseInt('{{current_page}}')
    var pagination_page = parseInt('{{pagination_page}}')
    document.onreadystatechange = function(){
        if (document.readyState === 'interactive') {
            on_page_load_pagination();
        }
    }
</script>
<div class="show__btn__option__export">
    <a href="{{url_for('GEN_XLSX_bp.download_xlsx_current_page', current_page_url = current_page)}}"><button>Export XLSX this page</button></a>
    <a href="{{url_for('GEN_XLSX_bp.download_xlsx_all')}}"><button>Export XLSX all row</button></a>
</div>
<div class="show__all__booking__room">
    <table>
        <tr>
            <th>No</th>
            <th>ID User</th>
            <th>ID Room</th>
            <th>Time Booking</th>
            <th>Time Start</th>
            <th>Default Service</th>
            <th>Option Service</th>
            <th>Minute Rent</th>
            <th>Status</th>
            <th>Total Price</th>
            <th>Option Service Price</th>
            <th>Code Booking</th>
            <th>Billing Option</th>
        </tr>
        {% for each_booking in get_all_booking %}
            <tr>
                <td>{{loop.index}}</td>
                <td>{{each_booking.id_users}}</td>
                <td>{{each_booking.id_all_room}}</td>
                <td>{{each_booking.time_booking}}</td>
                <td>{{each_booking.time_start}}</td>
                <td>
                    {% for each_default_service in each_booking.default_service %}
                        <p>{{each_default_service}}</p>
                    {% endfor %}
                </td>
                <td>
                    {% for each_option_service in each_booking.option_service %}
                        <p>{{each_option_service    }}</p>
                    {% endfor %}
                </td>
                <td>{{each_booking.minute_rent}}</td>
                <td>{{each_booking.status}}</td>
                <td>{{each_booking.total_price}}</td>
                <td>{{each_booking.option_service_price}}</td>
                <td>{{each_booking.code_booking}}</td>
                <td>{{each_booking.billing_option}}</td>
            </tr>
        {% endfor %}
    </table>
    <div class="show__pagination__page">
        {% if pagination_page > 5 %}
            <button id="btn__first__pagination__page" onclick="first_page_pagination()">Go to page 1</button>
            <button id='btn__previous__pagination' onclick="pre_btn_pagination()">Previous</button>
            {% for pagination in range(0, pagination_page) %}
                {% if current_page == pagination + 1 %}
                    <a href="{{url_for('GEN_XLSX_bp.generate_xlsx', current_page_url = pagination + 1)}}">
                        <button class="btn__pagination active__btn__pagination" id="btn__page__pagination__page{{pagination + 1}}">{{pagination + 1}}</button>
                    </a>
                {% else %}
                    <a href="{{url_for('GEN_XLSX_bp.generate_xlsx', current_page_url = pagination + 1)}}">
                        <button class="btn__pagination" id="btn__page__pagination__page{{pagination + 1}}">{{pagination + 1}}</button>
                    </a>
                {% endif %}
            {% endfor %}
            <button id="btn__next__pagination" onclick="next_btn_pagination()">Next</button>
            <button id="btn__end__pagination__page" onclick="last_page_pagination()">Go to page end</button>
        {% else %}
            {% for pagination in range(0, pagination_page) %}
                {% if current_page == pagination + 1 %}
                    <a href="{{url_for('GEN_XLSX_bp.generate_xlsx', current_page_url = pagination + 1)}}">
                        <button class="btn__pagination active__btn__pagination" id="btn__page__pagination__page{{pagination + 1}}">{{pagination + 1}}</button>
                    </a>
                {% else %}
                    <a href="{{url_for('GEN_XLSX_bp.generate_xlsx', current_page_url = pagination + 1)}}">
                        <button class="btn__pagination" id="btn__page__pagination__page{{pagination + 1}}">{{pagination + 1}}</button>
                    </a>
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>
</div>