admin_blueprint/admin_blueprint.py
from flask import Blueprint, render_template, session, redirect, url_for, request

from . import exec_data
from . import draw_chart

admin_blueprint = Blueprint('ADMIN_bp', __name__, static_folder = 'static', template_folder = 'templates')

@admin_blueprint.route('/homepage-admin')
def homepage_admin():

    return render_template('homepage_admin.html')

@admin_blueprint.route('/log-out-admin')
def log_out_admin():
    session.clear()
    return redirect(url_for('HP_bp.homepage_page'))

@admin_blueprint.route('/all-users/show-all/<int:current_page>', methods = ['GET', 'POST'])
def show_all_users(current_page):
    if request.method == 'POST':
        if 'submit_delete_user' in request.form:
            post_id_user = request.form['value_delete_user']
            exec_del_user_by_id = exec_data.post_del_user(post_id_user)

            if exec_del_user_by_id == True:
                return redirect(url_for('ADMIN_bp.show_all_users', current_page = 1, msg_del_user_by_id_success = 'True'))
            else:
                return redirect(url_for('ADMIN_bp.show_all_users', current_page = 1, msg_del_user_by_id_fail = 'True'))

        elif 'submit_edit_user' in request.form:
            post_id_user = request.form['value_edit_user']
            return redirect(url_for('ADMIN_bp.edit_user_by_id', user_id_url = post_id_user))

    return_para = {}

    msg_del_user_by_id_success = request.args.get('msg_del_user_by_id_success')
    msg_del_user_by_id_fail = request.args.get('msg_del_user_by_id_fail')
    msg_edit_user_by_id_success = request.args.get('msg_edit_user_by_id_success')
    msg_edit_user_by_id_fail = request.args.get('msg_edit_user_by_id_fail')

    if msg_del_user_by_id_success is not None:
        return_para['msg_del_user_by_id_success'] = 'Xóa thành công'
    if msg_del_user_by_id_fail is not None:
        return_para['msg_del_user_by_id_fail'] = 'Xóa thất bại'
    if msg_edit_user_by_id_success is not None:
        return_para['msg_edit_user_by_id_success'] = 'Chỉnh sửa thành công'
    if msg_edit_user_by_id_fail is not None:
        return_para['msg_edit_user_by_id_fail'] = 'Chỉnh sửa thất bại'
        
    get_all_user = exec_data.get_all_users(current_page_para = current_page)

    if get_all_user != False:
        return_para['get_all_user'] = get_all_user['get_all_user']

    return render_template('admin_show_all_user.html', **return_para)

@admin_blueprint.route('/all-users/edit-user/<user_id_url>', methods = ['GET', 'POST'])
def edit_user_by_id(user_id_url):
    if request.method == 'POST':
        if 'submit_edit_user' in request.form:
            tel_edit_user = request.form['input_tel_user']
            gmail_edit_user = request.form['input_gmail_user']

            exec_update_user = exec_data.post_edit_user_by_id(id_user_para = user_id_url, gmail_user_para = gmail_edit_user, tel_user_para = tel_edit_user)

            if exec_update_user == True:
                return redirect(url_for('ADMIN_bp.show_all_users', current_page = 1, msg_edit_user_by_id_success = 'True'))
            else:
                return redirect(url_for('ADMIN_bp.show_all_users', current_page = 1, msg_edit_user_by_id_fail = 'True'))

    return_para = {}

    get_user_by_id = exec_data.get_user_by_id(user_id_url)

    if get_user_by_id != False:
        return_para['get_user_by_id'] = get_user_by_id['get_user_by_id']

    return render_template('edit_user_name.html', **return_para)

@admin_blueprint.route('/all-editor/show_all/<int:current_page_url>', methods = ['GET', 'POST'])
def show_all_editor(current_page_url):
    if request.method == 'POST':
        if 'submit_delete_editor' in request.form:
            post_id_editor = request.form['value_delete_editor']
            exec_del_editor_by_id = exec_data.post_del_editor(post_id_editor)

            if exec_del_editor_by_id == True:
                return redirect(url_for('ADMIN_bp.show_all_editor', current_page_url = 1, msg_del_editor_by_id_success = 'True'))
            else:
                return redirect(url_for('ADMIN_bp.show_all_editor', current_page_url = 1, msg_del_editor_by_id_fail = 'True'))

        elif 'submit_edit_editor' in request.form:
            post_id_editor = request.form['value_edit_editor']
            return redirect(url_for('ADMIN_bp.edit_editor_by_id', editor_id_url = post_id_editor))

    return_para = {}

    msg_del_editor_by_id_success = request.args.get('msg_del_editor_by_id_success')
    msg_del_editor_by_id_fail = request.args.get('msg_del_editor_by_id_fail')

    if msg_del_editor_by_id_success is not None:
        return_para['msg_del_editor_by_id_success'] = 'Xóa thành công'
    if msg_del_editor_by_id_fail is not None:
        return_para['msg_del_editor_by_id_fail'] = 'Xóa thất bại'

    get_all_editor = exec_data.get_all_editor(current_page_url)

    if get_all_editor != False:
        return_para['get_all_editor'] = get_all_editor['get_all_editor']

    return render_template('show_all_editor.html', **return_para)

@admin_blueprint.route('/all-editor/edit-editor/<editor_id_url>', methods = ['GET', 'POST'])
def edit_editor_by_id(editor_id_url):
    if request.method == 'POST':
        if 'submit_edit_editor' in request.form:
            tel_edit_editor = request.form['input_tel_editor']
            gmail_edit_editor = request.form['input_gmail_editor']

            exec_update_editor = exec_data.post_edit_editor_by_id(id_editor_para = editor_id_url, gmail_editor_para = gmail_edit_editor, tel_editor_para = tel_edit_editor)

            if exec_update_editor == True:
                return redirect(url_for('ADMIN_bp.show_all_editor', current_page_url = 1, msg_edit_editor_by_id_success = 'True'))
            else:
                return redirect(url_for('ADMIN_bp.show_all_editor', current_page_url = 1, msg_edit_editor_by_id_fail = 'True'))

    return_para = {}

    get_editor_by_id = exec_data.get_editor_by_id(editor_id_url)

    if get_editor_by_id != False:
        return_para['get_editor_by_id'] = get_editor_by_id['get_editor_by_id']

    return render_template('edit_editor_name.html', **return_para)

@admin_blueprint.route('/static/homepage-static')
def homepage_static_admin():
    return_para = {}

    get_booking_room_by_pending_status = exec_data.get_booking_room_by_pending_status()
    get_booking_room_by_cancel_status = exec_data.get_booking_room_by_cancel_status()
    get_booking_room_by_finish_status = exec_data.get_booking_room_by_finish_status()

    if ((get_booking_room_by_pending_status != False) and (get_booking_room_by_cancel_status != False) and (get_booking_room_by_finish_status != False)):
        base64_img_bar_chart_count_status_booking_room = draw_chart.bar_chart_count_status_booking_room(get_booking_room_by_pending_status['length_booking_room_pending_status'],
            get_booking_room_by_cancel_status['length_booking_room_cancel_status'], get_booking_room_by_finish_status['length_booking_room_finish_status'])

        return_para['base64_img_bar_chart_count_status_booking_room'] = base64_img_bar_chart_count_status_booking_room

    return render_template('homepage_static_admin.html', **return_para)

admin_blueprint/templates/admin_show_all_user.html
{% extends 'homepage_admin.html' %}

{% block content_homepage_admin %}
    <link rel="stylesheet" href="{{url_for('ADMIN_bp.static', filename = 'css/admin_show_all_user.css')}}">
    <script src="{{url_for('ADMIN_bp.static', filename = 'javascript/admin_show_all_user.js')}}"></script>

    <div class="show__all__user">
        {% if msg_del_user_by_id_success is defined %}
            <div class="msg__del__user__id__success">
                <p>{{msg_del_user_by_id_success}}</p>
            </div>
        {% endif %}
        {% if msg_del_user_by_id_fail is defined %}
            <div class="msg__del__user__id__fail">
                <p>{{msg_del_user_by_id_fail}}</p>
            </div>
        {% endif %}
        {% if msg_edit_user_by_id_success is defined %}
            <div class="msg__edit__user__id__success">
                <p>{{msg_edit_user_by_id_success}}</p>
            </div>
        {% endif %}
        {% if msg_edit_user_by_id_fail is defined %}
            <div class="msg__edit__user__id__fail">
                <p>{{msg_edit_user_by_id_fail}}</p>
            </div>
        {% endif %}
        <table>
            <caption>All Users</caption>
            <tr>
                <th>No</th>
                <th>Full Name</th>
                <th>Telephone</th>
                <th>Gmail</th>
                <th>Gender</th>
                <th>Status</th>
                <th>Delete Each User</th>
                <th>Edit Each User</th>
            </tr>
            {% for each_users in get_all_user %}
                <tr>
                    <td>{{loop.index}}</td>
                    <td>{{each_users.full_name}}</td>
                    <td>{{each_users.tel}}</td>
                    <td>{{each_users.gmail}}</td>
                    <td>{{each_users.gender}}</td>
                    <td>{{each_users.status}}</td>
                    <td>
                        <button class="btn__table__all__user" onclick="confirm_del_user('{{each_users.id}}')" type="button">Delete</button>
                    </td>
                    <td>
                        <button class="btn__table__all__user" onclick="confirm_edit_user('{{each_users.id}}')" type="button">Edit</button>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <div hidden>
        <form method="post">
            <input type="text" name="value_delete_user" class="value__delete__user">
            <input type="text" name="value_edit_user" class="value__edit__user">

            <input type="submit" name="submit_delete_user" class="submit__delete__user">
            <input type="submit" name="submit_edit_user" class="submit__edit__user">
        </form>
    </div>
{% endblock %}

admin_blueprint/templates/edit_editor_name.html
{% extends 'homepage_admin.html' %}

{% block content_homepage_admin %}
    <link rel="stylesheet" href="{{url_for('ADMIN_bp.static', filename = 'css/edit_editor_name.css')}}">
    <form method="post">
        <div class="edit__user__by__id">
            <table>
                <caption>Edit Editor {{get_editor_by_id.full_name}}</caption>
                <tr>
                    <th>Telephone</th>
                    <th>Gmail</th>
                </tr>
                <tr>
                    <td>
                        <input type="tel" name="input_tel_editor">
                    </td>
                    <td>
                        <input type="text" name="input_gmail_editor">
                    </td>
                </tr>
            </table>
        </div>
        <input type='submit' name="submit_edit_editor">
    </form>
{% endblock %}

admin_blueprint/templates/edit_user_name.html
{% extends 'homepage_admin.html' %}

{% block content_homepage_admin %}
    <link rel="stylesheet" href="{{url_for('ADMIN_bp.static', filename = 'css/edit_user_name.css')}}">
    <form method="post">
        <div class="edit__user__by__id">
            <table>
                <caption>Edit User {{get_user_by_id.full_name}}</caption>
                <tr>
                    <th>Telephone</th>
                    <th>Gmail</th>
                </tr>
                <tr>
                    <td>
                        <input type="tel" name="input_tel_user">
                    </td>
                    <td>
                        <input type="text" name="input_gmail_user">
                    </td>
                </tr>
            </table>
        </div>
        <input type='submit' name="submit_edit_user">
    </form>
{% endblock %}

admin_blueprint/templates/homepage_admin.html
<link rel="stylesheet" href="{{url_for('ADMIN_bp.static', filename = 'css/homepage_admin.css')}}">
<header>
    <div class="header__inner">
        <div class="header__inner__img">
            <a href="{{url_for('ADMIN_bp.homepage_admin')}}">
                <img src="{{url_for('ADMIN_bp.static', filename = 'images/Logo-black.png')}}" alt="image-header">
            </a>
        </div>
        <div class="header__inner__option">
            <a href="{{url_for('ADMIN_bp.show_all_users',current_page = 1)}}" class="header__inner__link">Users</a>
            <a href="{{url_for('ADMIN_bp.show_all_editor',current_page_url = 1)}}" class="header__inner__link">Editor</a>
            <a href="{{url_for('ADMIN_bp.homepage_static_admin')}}" class="header__inner__link">Static</a>
        </div>
        <div class="header__inner__log__out">
            <a href="{{url_for('ADMIN_bp.log_out_admin')}}" class="header__inner__link">Log out</a>
        </div>
    </div>
</header>
{% block content_homepage_admin %}

{% endblock %}

admin_blueprint/templates/homepage_static_admin.html
{% extends 'homepage_admin.html' %}

{% block content_homepage_admin %}
    <link rel="stylesheet" href="{{url_for('ADMIN_bp.static', filename = 'css/homepage_static_admin.css')}}">
    <div class="export__homepage__static__admin">
        <a href="{{url_for('GEN_XLSX_bp.generate_xlsx', current_page_url = 1)}}" class="link__export__static">Export To CSV</a>
        <a href="{{url_for('GEN_PDF_bp.generate_pdf', current_page_url = 1)}}" class="link__export__static">Export to PDF</a>
    </div>
    <img src="data:image/png;base64,{{base64_img_bar_chart_count_status_booking_room}}">
{% endblock %}

admin_blueprint/templates/show_all_editor.html
{% extends 'homepage_admin.html' %}

{% block content_homepage_admin %}
    <link rel="stylesheet" href="{{url_for('ADMIN_bp.static', filename = 'css/show_all_editor.css')}}">
    <script src="{{url_for('ADMIN_bp.static', filename = 'javascript/show_all_editor.js')}}"></script>

    <div class="show__all__editor">
        {% if msg_del_editor_by_id_success is defined %}
            <div class="msg__del__editor__id__success">
                <p>{{msg_del_editor_by_id_success}}</p>
            </div>
        {% endif %}
        {% if msg_del_editor_by_id_fail is defined %}
            <div class="msg__del__editor__id__fail">
                <p>{{msg_del_editor_by_id_fail}}</p>
            </div>
        {% endif %}
        {% if msg_edit_editor_by_id_success is defined %}
            <div class="msg__edit__editor__id__success">
                <p>{{msg_edit_editor_by_id_success}}</p>
            </div>
        {% endif %}
        {% if msg_edit_editor_by_id_fail is defined %}
            <div class="msg__edit__editor__id__fail">
                <p>{{msg_edit_editor_by_id_fail}}</p>
            </div>
        {% endif %}
        <table>
            <caption>All Editor</caption>
            <tr>
                <th>No</th>
                <th>Full Name</th>
                <th>Telephone</th>
                <th>Gmail</th>
                <th>Gender</th>
                <th>Status</th>
                <th>Delete Each Editor</th>
                <th>Edit Each Editor</th>
            </tr>
            {% for each_editor in get_all_editor %}
                <tr>
                    <td>{{loop.index}}</td>
                    <td>{{each_editor.full_name}}</td>
                    <td>{{each_editor.tel}}</td>
                    <td>{{each_editor.gmail}}</td>
                    <td>{{each_editor.gender}}</td>
                    <td>{{each_editor.status}}</td>
                    <td>
                        <button class="btn__table__all__editor" onclick="confirm_del_editor('{{each_editor.id}}')" type="button">Delete</button>
                    </td>
                    <td>
                        <button class="btn__table__all__editor" onclick="confirm_edit_editor('{{each_editor.id}}')" type="button">Edit</button>
                    </td>
                </tr>
            {% endfor %}
        </table>
    </div>
    <div hidden>
        <form method="post">
            <input type="text" name="value_delete_editor" class="value__delete__editor">
            <input type="text" name="value_edit_editor" class="value__edit__editor">

            <input type="submit" name="submit_delete_editor" class="submit__delete__editor">
            <input type="submit" name="submit_edit_editor" class="submit__edit__editor">
        </form>
    </div>
{% endblock %}