user_blueprint/user_blueprint.py
from flask import Blueprint, render_template, session, redirect, url_for, request
from firebase_admin import storage
import ast
import base64
from datetime import datetime, timedelta
import json
from dotenv import load_dotenv
import os
import jwt

from . import exec_data

user_blueprint = Blueprint('USER_bp', __name__, static_folder = 'static', template_folder = 'templates')

@user_blueprint.before_request
def check_current_token():
    if 'token_rr_2023' not in session:
        return redirect(url_for('Login_bp.login_account'))
        
    load_dotenv()
    secret_key = os.getenv('secret_key')
    decode_token = jwt.decode(session['token_rr_2023'], secret_key, algorithms = ["HS256"])
    current_time = datetime.now()
    end_time_token = datetime.strptime(decode_token['end_time_token'], f'%d-%m-%Y %H:%M:%S')

    if current_time < end_time_token:
        role_user_temp = decode_token['role_user']
        if role_user_temp == 'user':
            session['role_user_rr_2023'] = 'user'
            session['id_user'] = decode_token['id_login']
        else:
            return "<p>You are not login at role user, so you can't access this page</p>"
    else:
        return redirect(url_for('Login_bp.login_account'))

def download_img_from_firebase(remote_file_name):
    bucket = storage.bucket()
    blob = bucket.blob(remote_file_name)
    image_data = blob.download_as_bytes()
    base64_img = base64.b64encode(image_data).decode()
    return base64_img

@user_blueprint.route('/log-out-user')
def log_out_user():
    session.clear()
    return redirect(url_for('HP_bp.homepage_page'))
 
@user_blueprint.route('/homepage-user/type/<type_room>/<int:current_page_para>')
def type_room_homepage(type_room = None, current_page_para = 1):
    return_para = {}
    lst_base64_image_firebase = []

    if type_room == 'big':
        get_type_room = exec_data.get_type_room(type_room_para = 'big', current_page_para = current_page_para)
    elif type_room == 'medium':
        get_type_room = exec_data.get_type_room(type_room_para = 'medium', current_page_para = current_page_para)
    elif type_room == 'small':
        get_type_room = exec_data.get_type_room(type_room_para = 'small', current_page_para = current_page_para)
    elif type_room == 'all':
        get_type_room = exec_data.get_type_room(type_room_para = 'all', current_page_para = current_page_para)
    else:
        return "Đường dẫn sai rồi nè :v"
    
    if get_type_room != False:
        return_para['get_type_room'] = get_type_room['get_type_room']
        return_para['lst_price'] = get_type_room['lst_price']

    # for each_image_firebase in get_type_room['lst_name_image_firebase']:
    #     dict_image_temp = ast.literal_eval(each_image_firebase)
    #     for each_image in dict_image_temp:
    #         base64_str = download_img_from_firebase(dict_image_temp[each_image])
    #         dict_image_temp[each_image] = base64_str
    #     lst_base64_image_firebase.append(dict_image_temp)

    # return_para['lst_base64_image_firebase'] = lst_base64_image_firebase

    return_para['current_page'] = current_page_para
    return_para['pagination_page'] = get_type_room['pagination_page']
    return_para['type_room'] = type_room

    return render_template('type_room_homepage.html', **return_para)

@user_blueprint.route('/homepage-user/addr/<province_para>/<int:current_page_para>')
def province_room_homepage(province_para, current_page_para = 1):
    return_para = {}
    lst_base64_image_firebase = []
    get_province_room = exec_data.get_room_by_province(province_para, current_page_para = current_page_para)

    if get_province_room != False:
        return_para['province_room'] = get_province_room['get_room_by_province']
        return_para['lst_price'] = get_province_room['lst_price']

    # for each_image_firebase in get_province_room['lst_name_image_firebase']:
    #     dict_image_temp = ast.literal_eval(each_image_firebase)
    #     for each_image in dict_image_temp:
    #         base64_str = download_img_from_firebase(dict_image_temp[each_image])
    #         dict_image_temp[each_image] = base64_str
    #     lst_base64_image_firebase.append(dict_image_temp)

    # return_para['lst_base64_image_firebase'] = lst_base64_image_firebase

    return_para['current_page'] = int(current_page_para)
    return_para['pagination_page'] = get_province_room['pagination_page']
    return_para['province_para'] = province_para

    return render_template('province_room_homepage.html', **return_para)

# This route show information about the room, show detail and all information about one room
# each room have each code random separate, so we use code_random for get information from database
@user_blueprint.route('/details-room/<code_room>', methods = ['GET', 'POST'])
def detail_room(code_room):
    if request.method == 'POST':
        if 'submit__booking__room' in request.form:
            date_rent_room = request.form['choose_date_rent_room']
            minute_rent_room = request.form['minute_rent_room']
            id_rent_room = request.form['choose_id_rent_room']
            id_user = session['id_user']

            billing_option = request.form['billing_option']
            get_total_price_rent_room = request.form['total_price_rent_room']
            get_option_service_price = request.form['get_option_service_price']

            dict_default_service = ast.literal_eval(request.form['choose_default_service_dict']) 
            dict_option_service = ast.literal_eval(request.form['choose_option_service_dict'])
            
            ins_booking_room = exec_data.post_new_booking_room(id_user_para = id_user, id_all_room_para = id_rent_room,
                time_start_para = date_rent_room, default_service_para = dict_default_service, 
                option_service_para = dict_option_service, minute_rent_para = minute_rent_room, total_price_para = get_total_price_rent_room,
                option_service_price_para = get_option_service_price, note_booking_para = "", billing_option_para = billing_option)
            
            if ins_booking_room == True:
                return redirect(url_for('USER_bp.detail_room', code_room = code_room, msg_ins_new_booking_room = True))
            else:
                return redirect(url_for('USER_bp.detail_room', code_room = code_room, msg_ins_new_booking_room = False))

    return_para = {}  

    # Request.args.get try to find parameter msg_ins_new_booking_room, if not defined return None otherwise return msg_ins_new_booking_room para
    msg_ins_new_booking_room = request.args.get('msg_ins_new_booking_room')
    if msg_ins_new_booking_room is not None:
        if msg_ins_new_booking_room == 'True':
            return_para['success_ins_new_booking_room'] = 'Đặt phòng họp thành công'
        else:
            return_para['fail_ins_new_booking_room'] = 'Đặt phòng họp thất bại'


    get_room_by_code_room = exec_data.get_detail_room_by_code_room(code_room)
    get_duration_room = get_room_by_code_room['get_duration_room']

    # each room in database have id_duration column, foreign key to duration table
    # 1 duration have start time and end time for use this room
    # 1 room can use in some seconds
    # so we need to check the room, if the room in valid duration, ok , can rent the room, otherwise not rent room 
    start_time_duration_room = get_duration_room[2]
    end_time_duration_room = get_duration_room[3]
    second_duration_room = int(get_duration_room[1])
    current_time_now = datetime.now() + timedelta(seconds = second_duration_room)
    
    if (start_time_duration_room <= current_time_now <= end_time_duration_room) == True:
        return_para['valid_duration_room'] = True
        return_para['start_time_duration_room'] = start_time_duration_room
        return_para['end_time_duration_room'] = end_time_duration_room
        return_para['minute_duration_room'] = get_duration_room[1]
        return_para['default_service_dict'] = get_room_by_code_room['default_service_dict']
        return_para['option_service_dict'] = get_room_by_code_room['option_service_dict']
    else:
        return_para['valid_duration_room'] = False

    if get_room_by_code_room != False:
        return_para['get_room_by_code_room'] = get_room_by_code_room['get_room_by_code_room']
        return_para['price_room'] = get_room_by_code_room['price_room'][1]
        return_para['lst_name_image_firebase'] = get_room_by_code_room['lst_name_image_firebase']
    
    # ast.literal_eval
    return render_template('detail_room.html', **return_para)

@user_blueprint.route('/valid-rent-room/type/<type_room>/<int:current_page_para>')
def valid_rent_room_type(type_room = None, current_page_para = 1):
    return_para = {}

    if type_room == 'all':
        get_valid_rent_room = exec_data.get_valid_duration_room_type(type_room_para = 'all', current_page_para = current_page_para)
    elif type_room == 'small':
        get_valid_rent_room = exec_data.get_valid_duration_room_type(type_room_para = 'small', current_page_para = current_page_para)
    elif type_room == 'medium':
        get_valid_rent_room = exec_data.get_valid_duration_room_type(type_room_para = 'medium', current_page_para = current_page_para)
    elif type_room == 'big':
        get_valid_rent_room = exec_data.get_valid_duration_room_type(type_room_para = 'big', current_page_para = current_page_para)

    return_para['lst_valid_duration_room'] = get_valid_rent_room['lst_valid_duration_room']
    return_para['lst_price'] = get_valid_rent_room['lst_price']
    return_para['lst_name_image_firebase'] = get_valid_rent_room['lst_name_image_firebase']
    return_para['lst_duration_room_status'] = get_valid_rent_room['lst_duration_room_status']

    return_para['current_page'] = current_page_para
    return_para['pagination_page'] = get_valid_rent_room['pagination_page']
    return_para['type_room'] = type_room

    return render_template('valid_rent_room_type.html', **return_para)

user_blueprint/templates/base_user_page.html
<link rel="stylesheet" href="{{url_for('USER_bp.static', filename = 'css/base_user_page.css')}}">
<script src="{{url_for('USER_bp.static', filename = 'javascript/base_user_page.js')}}"></script>
<header>
    <div class="each__header__inner">
        <img src="{{url_for('USER_bp.static', filename = 'images/Logo.png')}}" id="logo__header__img" alt="logo image">
    </div>
    <div class="each__header__inner header__search">
        <input type="text" name="header__user__search" id="input__header__search" placeholder="Tìm Kiếm">
        <input type="submit" name="submit__header__user__search" id="submit__header__user__search" value="Search">
    </div>
    <div>
        <img src="{{url_for('USER_bp.static', filename = 'images/avatar-account.png')}}" id="avatar__account__img" alt="avatar image">
        <a href="{{url_for('USER_bp.log_out_user')}}">Log out</a>
    </div>
</header>
<div class="content__user__page">
    <div class="left__content">
        <div class="option__left__content">
            <img src="{{url_for('USER_bp.static', filename = 'images/icon-homepage.png')}}" alt="icon image" class="icon__image__left__content">
            <a href="{{url_for('USER_bp.type_room_homepage', type_room = 'all', current_page_para = 1)}}" class="left__content__link">Trang chủ</a>
        </div>
        {#<div class="option__left__content">
            <img src="{{url_for('USER_bp.static', filename = 'images/icon-room.png')}}" alt="icon image" class="icon__image__left__content">
            <a href="#" class="left__content__link">Đặt phòng</a>
        </div>#}
        <div class="option__left__content">
            <img src="{{url_for('USER_bp.static', filename = 'images/icon-empty.png')}}" alt="icon image" class="icon__image__left__content">
            <a href="{{url_for('USER_bp.valid_rent_room_type', type_room = 'all', current_page_para = 1)}}" class="left__content__link">Phòng đang trống</a>
        </div>
        <div class="option__left__content">
            <img src="{{url_for('USER_bp.static', filename = 'images/icon-control.png')}}" alt="icon image" class="icon__image__left__content">
            <a href="{{url_for('USER_bp.show_all_rent_room', current_page_para = 1)}}" class="left__content__link">Quản lý đơn thuê</a>
        </div>
    </div>
    <div class="right__content">
        {% block content_user_page %}

        {% endblock %}
    </div>
</div>

user_blueprint/templates/detail_room.html
<link rel="stylesheet" href="{{url_for('USER_bp.static', filename = 'css/detail_room.css')}}">
<script src="{{url_for('USER_bp.static', filename = 'javascript/detail_room.js')}}"></script>
{% if valid_duration_room == True %}
    <script>
        var start_time_duration_room = "{{start_time_duration_room}}"
        var end_time_duration_room = "{{end_time_duration_room}}"
        var minute_duration_room = "{{minute_duration_room}}"
        var dict_default_service_room = {}
        var dict_option_service_room = {}
        let value_amount;
        let value_price
    </script>
{% endif %}
<header>
    <a href="{{url_for('USER_bp.type_room_homepage', type_room = 'all', current_page_para = 1)}}">
        <img src="{{url_for('USER_bp.static', filename = 'images/Logo.png')}}" id="img__logo__header">
    </a>
    <a href="{{url_for('USER_bp.log_out_user')}}" id="log__out__header__btn">Log out</a>
</header>
{% if success_ins_new_booking_room is defined %}
    <div class="success__msg__ins__new__booking__room">
        <p>{{success_ins_new_booking_room}}</p>
    </div>
{% endif %}
{% if fail_ins_new_booking_room is defined %}
    <div class="fail__msg__ins__new__booking__room">
        <p>{{fail_ins_new_booking_room}}</p>
    </div>
{% endif %}
{% if get_room_by_code_room is defined %}
    <div class="basic__inform__room">
        <div class="img__detail__room">
            <img src="{{url_for('USER_bp.static', filename = 'images/detail-image-1.jpg')}}" id="main__img__detail__room">
            <div class="another__img__detail__room">
                <img src="{{url_for('USER_bp.static', filename = 'images/detail-image-2.jpg')}}">
                <img src="{{url_for('USER_bp.static', filename = 'images/detail-image-3.jpg')}}">
                <img src="{{url_for('USER_bp.static', filename = 'images/detail-image-4.jpg')}}">
            </div>
        </div>
        <div class="right__basic__inform">
            <form method="post">
                <div class="name__addr__detail__room">
                    <h3 id="name__room__title">{{get_room_by_code_room[2]}}</h3>
                    <div class="addr__detail__room">
                        <div>
                            <img src="{{url_for('USER_bp.static', filename = 'images/icon-address.png')}}">
                            <p id="full__addr__detail__room">{{get_room_by_code_room[8]}}, {{get_room_by_code_room[7]}}, {{get_room_by_code_room[6]}}</p>
                        </div>
                    </div>
                </div>
                <div class="price__btn__booking__detail__room">
                    <p id="price__detail__room__title">{{price_room}} vnđ</p>
                    {% if valid_duration_room == True %}
                        <input type="submit" id="btn__submit__booking__room" value="Booking" name="submit__booking__room"></input>
                    {% endif %}
                </div>
                {% if valid_duration_room == True %}
                    <div class="show__each__price__room">
                        <p>Tiền phòng : <span class="price__detail__room">{{price_room}}</span> vnđ</p>
                        <p>Tiền dịch vụ mặc định : <span class="price__default__service">0</span> vnđ</p>
                        <p>Tiền dịch vụ tự chọn : <span class="price__option__service">0</span> vnđ</p>
                        <ul class="price__each__option__service">

                        </ul>
                    </div>
                    <div class="show__duration__room">
                        <div>
                            <label>Start duration :</label>
                            <p>{{start_time_duration_room}}</p>
                        </div>
                        <div>
                            <label>End Duration :</label>
                            <p>{{end_time_duration_room}}</p>
                        </div>
                        <div>
                            <label>Minute Rent :</label>
                            <p>{{minute_duration_room}} minutes</p>
                        </div>
                    </div>
                    <div class="choose__date__use__room">
                        <div>
                            <label>Chọn ngày giờ : </label>
                            <input type="datetime-local" oninput="choose_date_rent_room_js()" class="choose__date__rent__room" name="choose_date_rent_room">
                        </div>
                        <div>
                            <label>Thời gian dùng phòng : <i>(Minute)</i></label>
                            <input type="number" name="minute_rent_room" class="choose__duration__rent__room" oninput="choose_date_rent_room_js()" max="{{minute_duration_room}}" min = "1">
                        </div>
                    </div>
                    <p class="valid__condition__rent__room__title">Bạn không thể thuê vì chưa đủ điều kiện thời gian</p>
                    <p id="title__choose__default__option__service">Choose Default Service & Option Service</p>
                    <div class="choose__service__detail__room">
                        <div class="choose__default__service__room">
                            <select name="choose_default_service" class="select__choose__default__service">
                                <option name="not-choose-default-service">Choose Default Service</option>
                                {% for default_service in default_service_dict %}
                                    <script>
                                        dict_default_service_room['{{default_service}}'] = parseInt("{{default_service_dict[default_service]}}")
                                    </script>
                                    <option value="{{default_service}}">{{default_service}}</option>
                                {% endfor %}
                            </select>
                            <button type="button" class="btn__add__service__room" onclick="add_default_service()">Add</button>
                        </div>
                        {% for option_service in option_service_dict %}
                            <script>
                                value_amount = "{{option_service_dict[option_service]['amount']}}"
                                value_price = "{{option_service_dict[option_service]['price']}}"
                                dict_option_service_room["{{option_service}}"] = {'amount' : parseInt(value_amount), 'price' : value_price}
                            </script>
                        {% endfor %}
                        <div class="choose__option__service__room">
                            <select name="choose_option_service" class="select__choose__option__service">
                                <option name="not-choose-option-service">Choose Option Service</option>
                                {% for option_service in option_service_dict %}
                                    <option value="{{option_service}}">{{option_service}}</option>
                                {% endfor %}
                            </select>
                            <button type='button' class="btn__add__service__room" onclick="add_option_service()">Add</button>
                        </div>
                    </div>
                    <div class="show__add__service__room">
                        <p>Show Service</p>
                        <div class="show__add__service__room__inner">
                            <div class="show__service__default__add">
                                <p>Default Service</p>
                                <ul class="lst__default__service__add__room">

                                </ul>
                            </div>
                            <div class="show__service__option__add">
                                <p>Option Service</p>
                                <ul class="lst__option__service__add__room">

                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="billing__information__choose">
                        <p>Billing Information</p>
                        <div>
                            <input type="radio" name="billing_option" value="momo">MOMO
                        </div>
                        <div>
                            <input type="radio" name="billing_option" value="banking">Banking
                        </div>
                        <div>
                            <input type="radio" name="billing_option" value="money">Money
                        </div>
                    </div>
                {% else %}
                    <p id="not__valid__duration__room">Hiện tại phòng này đang không trong thời gian cho thuê</p>
                {% endif %}
                <input type="text" value='{{get_room_by_code_room[0]}}' name='choose_id_rent_room' hidden>
                <input type="text" value="" name="choose_default_service_dict" class="choose__default__service__dict" hidden>
                <input type="text" value="" name="choose_option_service_dict" class="choose__option__service__dict" hidden>
                <input type="text" value = "" name="total_price_rent_room" class="total__price__rent__room" hidden>
                <input type="text" value = "" name="get_option_service_price" class="get__option__service__price" hidden>
            </form>
        </div>
    </div>
    <div class="detail__inform__room">
        <h3 id="title__detail__inform__room">Mô tả chi tiết sản phẩm</h3>
        <hr>
        <p class="describe__detail__inform__room">Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias, quaerat!</p>
        <p class="describe__detail__inform__room">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quas dolorem eaque minus enim perferendis corporis eligendi quasi obcaecati adipisci pariatur! Pariatur reiciendis tempora nobis eaque repudiandae et praesentium repellendus eveniet!</p>
        <p class="describe__detail__inform__room">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Minima hic, odio fuga aut dicta expedita ipsa? Id iste fugiat ipsam.</p>
        <p class="describe__detail__inform__room">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Atque illo magni amet culpa est in voluptas sed, impedit cupiditate optio, doloribus, sapiente ipsum. Nihil repellat ipsa in rerum quae fugiat? Labore tempora, sed id aliquid vero cumque harum porro quas?</p>
        <img src="{{url_for('USER_bp.static', filename = 'images/detail-image-2.jpg')}}" class="img__detail__inform__room">
        <img src="{{url_for('USER_bp.static', filename = 'images/detail-image-3.jpg')}}" class="img__detail__inform__room">
        <img src="{{url_for('USER_bp.static', filename = 'images/detail-image-4.jpg')}}" class="img__detail__inform__room">
        <p class="describe__detail__inform__room">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Repellat quidem alias accusantium a enim deserunt itaque reiciendis aliquam quisquam totam.</p>
        <p class="describe__detail__inform__room">Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt facilis obcaecati culpa pariatur mollitia accusantium molestias repudiandae at. Reprehenderit eveniet, et enim dolorum corrupti, rem itaque, deserunt ipsa provident maxime animi? Delectus laboriosam quo totam minus aperiam, vel numquam quis minima aspernatur esse exercitationem maxime inventore incidunt. Magnam, exercitationem explicabo?</p>
    </div>
{% else %}
    <p>Có lỗi trong quá trình thực thi trang. Thử chạy lại trang web hoặc hãy liên hệ admin website để được hỗ trợ</p>
{% endif %}

user_blueprint/templates/homepage_user_page.html
{% extends 'base_user_page.html' %}

{% block content_user_page %}
    <div class="tag__right__content">
        <a href="{{url_for('USER_bp.type_room_homepage', type_room = 'all', current_page_para = 1)}}" class="tag__link__right__content" id="all__room__tag__homepage">All</a>
        <a href="{{url_for('USER_bp.type_room_homepage', type_room = 'small', current_page_para = 1)}}" class="tag__link__right__content" id="small__room__tag__homepage">Small</a>
        <a href="{{url_for('USER_bp.type_room_homepage', type_room = 'medium', current_page_para = 1)}}" class="tag__link__right__content" id="medium__room__tag__homepage">Medium</a>
        <a href="{{url_for('USER_bp.type_room_homepage', type_room = 'big', current_page_para = 1)}}" class="tag__link__right__content" id="big__room__tag__homepage">Big</a>
        <a href="{{url_for('USER_bp.province_room_homepage', province_para = 'ha_noi_vn', current_page_para = 1)}}" class="tag__link__right__content" id="ha__noi__room__tag__homepage">Ha Noi Capital</a>
        <a href="{{url_for('USER_bp.province_room_homepage', province_para = 'ho_chi_minh_vn', current_page_para = 1)}}" class="tag__link__right__content" id="ho__chi__minh__room__tag__homepage">Ho Chi Minh City</a>
        <a href="{{url_for('USER_bp.province_room_homepage', province_para = 'da_nang_vn', current_page_para = 1)}}" class="tag__link__right__content" id="da__nang__room__tag__homepage">Da Nang City</a>
    </div>
    <div>
        {% block homepage_user_page %}
        {% endblock %}
    </div>
{% endblock %}

user_blueprint/templates/province_room_homepage.html
{% extends 'homepage_user_page.html' %}

{% block homepage_user_page %}
    {% if province_room is defined %}
        {% if province_room|length != 0 %}
            <script src="{{url_for('USER_bp.static', filename = 'javascript/get_pagination.js')}}"></script>
            <link rel="stylesheet" href="{{url_for('USER_bp.static', filename = 'css/show_pagination_page.css')}}">
            <script>
                document.getElementsByClassName('option__left__content')[0].classList.add('active__left__content__link')
                var current_page = parseInt('{{current_page}}')
                var pagination_page = parseInt('{{pagination_page}}')
                document.onreadystatechange = function(){
                    if (document.readyState === 'interactive') {
                        on_page_load_pagination();
                    }
                }
            </script>
            {% if province_para == 'ha_noi_vn' %}
                <script>
                    document.getElementById('ha__noi__room__tag__homepage').classList.add('active__tag__right__content')
                </script>
            {% elif province_para == 'ho_chi_minh_vn' %}
                <script>
                    document.getElementById('ho__chi__minh__room__tag__homepage').classList.add('active__tag__right__content')
                </script>
            {% elif province_para == 'da_nang_vn' %}
                <script>
                    document.getElementById('da__nang__room__tag__homepage').classList.add('active__tag__right__content')
                </script>
            {% endif %}
            <div class="all__room__display">
                {% for each_room in province_room %}
                    <div class="each__room__display">
                        <a href="{{url_for('USER_bp.detail_room', code_room = each_room[1])}}" class="name__each__room__display">
                            <div class="blank__image__each__display">
                                {#<img src="data:image/png;base64,{{lst_base64_image_firebase[loop.index - 1]['1']}}">#}
                                <img src="{{url_for('USER_bp.static', filename = 'images/demo-room-images.png')}}">
                            </div>
                        </a>
                        <a href="{{url_for('USER_bp.detail_room', code_room = each_room[1])}}" class="name__each__room__display">{{each_room[2]}}</a>
                        <div class="inform__each__room">
                            <p id="addr__each__room">Xã {{each_room[8]}}, Huyện {{each_room[7]}}, Tỉnh {{each_room[6]}}</p>
                            <div class="capacity__type__inner">
                                <p>Sức chứa lớn nhất : {{each_room[3]}} người</p>
                                <p>Loại : {{each_room[5]}}</p>
                            </div>
                            <p>Gía thuê ( cơ bản ) : {{lst_price[loop.index - 1][1]}} triệu </p>
                        </div>
                    </div>
                {% endfor %}
            </div>
            
            <div class="show__pagination__page">
                {% if pagination_page > 5 %}
                    <button id="btn__first__pagination__page" onclick="first_page_pagination()">Go to page 1</button>
                    <button id='btn__previous__pagination' onclick="pre_btn_pagination()">Previous</button>
                    {% for pagination in range(0, pagination_page) %}
                        {% if current_page == pagination + 1 %}
                            <a href="{{url_for('USER_bp.province_room_homepage', province_para = province_para, current_page_para = pagination + 1)}}">
                                <button class="btn__pagination active__btn__pagination" id="btn__page__pagination__page{{pagination + 1}}">{{pagination + 1}}</button>
                            </a>
                        {% else %}
                            <a href="{{url_for('USER_bp.province_room_homepage', province_para = province_para, current_page_para = pagination + 1)}}">
                                <button class="btn__pagination" id="btn__page__pagination__page{{pagination + 1}}">{{pagination + 1}}</button>
                            </a>
                        {% endif %}
                    {% endfor %}
                    <button id="btn__next__pagination" onclick="next_btn_pagination()">Next</button>
                    <button id="btn__end__pagination__page" onclick="last_page_pagination()">Go to page end</button>
                {% else %}
                    {% for pagination in range(0, pagination_page) %}
                        {% if current_page == pagination + 1 %}
                            <a href="{{url_for('USER_bp.province_room_homepage', province_para = province_para, current_page_para = pagination + 1)}}">
                                <button class="btn__pagination active__btn__pagination" id="btn__page__pagination__page{{pagination + 1}}">{{pagination + 1}}</button>
                            </a>
                        {% else %}
                            <a href="{{url_for('USER_bp.province_room_homepage', province_para = province_para, current_page_para = pagination + 1)}}">
                                <button class="btn__pagination" id="btn__page__pagination__page{{pagination + 1}}">{{pagination + 1}}</button>
                            </a>
                        {% endif %}
                    {% endfor %}
                {% endif %}
            </div>
        {% elif province_room|length == 0 %}
            <p>chưa có phòng họp nào phù hợp loại phòng họp lớn</p>
        {% endif %}
    {% else %}
        <p>Không có phòng họp nào được tìm thấy</p>
    {% endif %}
{% endblock %}